### ISSUE TITLE
Dojo: Level 2, Probleme mit Pattern-Abfrage

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1512]
Im zweiten Raum im zweiten Level wird nach den Pattern gefragt. Hier sind mir folgende unschöne Dinge aufgefallen:

- [x] Die Eingabe wird _case-sensitive_ gematcht. Das sollte definitiv auf _case-insensitive_ geändert werden. => #1522

- [x] Die Eingabe wird nicht auf verschiedene typische (korrekte bzw. akzeptable) Schreibweisen gematcht. Beispiel: Die richtige Antwort wäre "Foo-Pattern" - dann sollten alle diese Schreibweisen akzeptiert werden: "Foo-Pattern", "Foopattern", "Foo Pattern", "Foo", "Foo-Muster", "Foo-Entwurfsmuster", "Foo Muster", "Foo Entwurfsmuster", jeweils _case-insensitive_ => #1522

- [x] Der Held sieht genauso aus wie der Wizard, mit dem man reden soll. Sollte der Held oder der Wizard eine andere Textur bekommen? => #1521

- [x] Die Stelle mit dem "Click here..." sollte beim tatsächlichen Aktivieren den vorgegebenen Text löschen. => #1524

- [ ] Nach einer bestimmten Anzahl von Fehleingaben wird das Spiel scheinbar beendet. Das ist für mich als Spieler aber nicht transparent. Hier sollte ein Gesundheitsbalken angezeigt werden, der mit jeder falschen Antwort kleiner wird. => #1523 (vgl. Kommentar https://github.com/Dungeon-CampusMinden/Dungeon/issues/1512#issuecomment-2096470868) 

Edit: (5) kann ich grad nicht mehr nachstellen - ich habe grad sehr viele Fehleingaben gemacht, ohne dass das Spiel beendet wurde. Kann es sein, dass mir da bei ersten Mal eine Exception den Garaus bereitet hatte? Also wieder mal eine der Art, die ihr so gern fangt und dann als Runtime-Exception weitergebt? Aber es gab auch keinen Stacktrace :/

**Comment by tgrothe** [comment]
> Edit: (5) kann ich grad nicht mehr nachstellen - ich habe grad sehr viele Fehleingaben gemacht, ohne dass das Spiel beendet wurde.

hm, also ist das Spiel abgestürzt nach den Eingaben? ohne == wobei?

**Comment by cagix** [comment]
> > Edit: (5) kann ich grad nicht mehr nachstellen - ich habe grad sehr viele Fehleingaben gemacht, ohne dass das Spiel beendet wurde.
> 
> hm, also ist das Spiel abgestürzt nach den Eingaben? ohne == wobei?

ich sag ja, ich kann es nicht mehr nachstellen. iirc hatte ich was richtiges in falscher schreibweise eingegeben, und dann war das spiel weg. kriege es aber nicht wiederholt :/ ...

**Comment by tgrothe** [comment]
> 3\. Der Held sieht genauso aus wie der Wizard, mit dem man reden soll. Sollte der Held oder der Wizard eine andere Textur bekommen?

Ich würde denken, der Wizard ... andernfalls wäre es verwirrend. Ein Ork-Schamane hat ja auch magische Fähigkeiten ...

**Comment by tgrothe** [comment]
> > > 3. Der Held sieht genauso aus wie der Wizard, mit dem man reden soll. Sollte der Held oder der Wizard eine andere Textur bekommen?
> > 
> > 
> > Ich würde denken, der Wizard ... andernfalls wäre es verwirrend. Ein Ork-Schamane hat ja auch magische Fähigkeiten ...
> 
> was halt einfacher geht ... ist ja am ende nicht wirklich relevant.

ja, denke ich auch ... und ein schamane ist ja so etwas ähnliches wie ein zauberer.

**Comment by tgrothe** [comment]
> > > Edit: (5) kann ich grad nicht mehr nachstellen - ich habe grad sehr viele Fehleingaben gemacht, ohne dass das Spiel beendet wurde.
> > 
> > 
> > hm, also ist das Spiel abgestürzt nach den Eingaben? ohne == wobei?
> 
> ich sag ja, ich kann es nicht mehr nachstellen. iirc hatte ich was richtiges in falscher schreibweise eingegeben, und dann war das spiel weg. kriege es aber nicht wiederholt :/ ...

@cagix könnte es vielleicht am anwachsenden arbeitsspeicher gelegen haben? bei mir trat es auch nicht mehr auf.

**Comment by cagix** [comment]
> > > > Edit: (5) kann ich grad nicht mehr nachstellen - ich habe grad sehr viele Fehleingaben gemacht, ohne dass das Spiel beendet wurde.
> > > 
> > > 
> > > hm, also ist das Spiel abgestürzt nach den Eingaben? ohne == wobei?
> > 
> > 
> > ich sag ja, ich kann es nicht mehr nachstellen. iirc hatte ich was richtiges in falscher schreibweise eingegeben, und dann war das spiel weg. kriege es aber nicht wiederholt :/ ...
> 
> @cagix könnte es vielleicht am anwachsenden arbeitsspeicher gelegen haben? bei mir trat es auch nicht mehr auf.

hmmm, vielleicht? wächst bei der aufgabe der ram-bedarf so stark an? aber ich habe nix bemerkt, was auf anwachsenden arbeitsspeicher hingedeutet hätte. normalerweise würde erst alles zäher werden und dann kommt irgendwann der lolipop von macos und dann wird was gestrichen. das war alles nicht.

**Comment by cagix** [comment]
@tgrothe was treibst du hier? reicht ein ticket nicht zum tracken?!

**Comment by tgrothe** [comment]
> @tgrothe was treibst du hier? reicht ein ticket nicht zum tracken?!

Schau mal hier https://github.com/Dungeon-CampusMinden/Dungeon/pull/1514#pullrequestreview-2039261660 du hattest geschrieben, dass es bitte in einzelnen pull requests umgesetzt werden sollte ("textur, string-vergleich, clickhandler"). Für mich war es naheliegend, dann aus diesem Ticket ein Sammelticket mit einzelnen Tasks zu machen.

**Comment by cagix** [comment]
> > @tgrothe was treibst du hier? reicht ein ticket nicht zum tracken?!
> 
> 
> 
> Schau mal hier https://github.com/Dungeon-CampusMinden/Dungeon/pull/1514#pullrequestreview-2039261660 du hattest geschrieben, dass es bitte in einzelnen pull requests umgesetzt werden sollte ("textur, string-vergleich, clickhandler"). Für mich war es naheliegend, dann aus diesem Ticket ein Sammelticket mit einzelnen Tasks zu machen.

ja genau: **pull-requests**. nicht _tickets_ 🤣

wir haben doch bereits das ticket mit verschiedenen punkten, und du hast bereits den code. warum verschwendest du nun zeit und machst aus dem ticket ein sammelticket und dann lauter einzeltickets, anstatt die pr's rauszuschieben und hier ggf. in den einzelnen punkten zu verlinken? der mist könnte längst erledigt sein.

**Comment by tgrothe** [comment]
> > > @tgrothe was treibst du hier? reicht ein ticket nicht zum tracken?!
> > 
> > 
> > Schau mal hier [#1514 (review)](https://github.com/Dungeon-CampusMinden/Dungeon/pull/1514#pullrequestreview-2039261660) du hattest geschrieben, dass es bitte in einzelnen pull requests umgesetzt werden sollte ("textur, string-vergleich, clickhandler"). Für mich war es naheliegend, dann aus diesem Ticket ein Sammelticket mit einzelnen Tasks zu machen.
> 
> ja genau: **pull-requests**. nicht _tickets_ 🤣
> 
> wir haben doch bereits das ticket mit verschiedenen punkten, und du hast bereits den code. warum verschwendest du nun zeit und machst aus dem ticket ein sammelticket und dann lauter einzeltickets, anstatt die pr's rauszuschieben und hier ggf. in den einzelnen punkten zu verlinken? der mist könnte längst erledigt sein.

ich habe einfach übersehen, dass man aus den einzelnen action tasks nicht unbedingt auch einzelne issues machen muss. 🙈

**Comment by cagix** [comment]
done.

**Comment by tgrothe** [comment]
> Nach einer bestimmten Anzahl von Fehleingaben wird das Spiel scheinbar beendet. Das ist für mich als Spieler aber nicht transparent. Hier sollte ein Gesundheitsbalken angezeigt werden, der mit jeder falschen Antwort kleiner wird. => nicht reproduzierbar

@cagix Habe den Fehler gefunden, wenn man die letzte Frage erneut aufruft und irgendetwas eingibt, was richtig oder falsch sein kann, dann wird immer der `currentPatternIndex` erhöht, und das Spiel stürzt mit einer AIOOBE ab.
